# For a reference to this file, see
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

# Rust toolchain releases can be found under
# https://rust-lang.github.io/rustup-components-history/

# Make sure to propagate version and component changes here to
# `.github/workflows/tests.yml` and to
# `.github/workflows/linting.yml` and to
# `.github/workflows/security.yml`!

[toolchain]
channel = 'nightly-2022-03-27'
components = [ 'cargo', 'rustc', 'rustfmt', 'rust-std', 'clippy' ]
