---
name: Code Quality Analysis

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/checks.yml
      - code/src/**
    branches: ['**']

defaults:
  run:
    shell: bash

env:
  RUST_TOOLCHAIN: nightly-2022-05-28

jobs:
  cargo_check:
    name: General Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      
      - name: Run 'cargo check'
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check

  cargo_format:
    name: Format Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt
          override: true

      - name: Run 'cargo fmt'
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all --message-format human -- --check

  cargo_clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
          override: true
      
      - name: Test cd
        run: cd code/

      - name: Run 'cargo clippy'
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --bin yourprojectname --lib --all-features -- -D warnings

  cargo_doc:
    name: Documentation Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2022-03-27
          override: true

      - name: Run 'cargo doc'
        uses: actions-rs/cargo@v1.0.1
        with:
          command: doc
          args: --lib --document-private-items
