---
name: Code Quality Analysis

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/checks.yml
      - code/src/**
    branches: ['**']

defaults:
  run:
    shell: bash

env:
  RUST_TOOLCHAIN: nightly-2022-05-28

jobs:
  cargo_check:
    name: General Check
    runs-on: ubuntu-20.04
    steps:
      - name: Install GitHub CI annotations formatter
        uses: olix0r/cargo-action-fmt@bf5a88a011c80288df07b34194f3f0abdb4b8f7d

      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Run `cargo fmt`
        run: |
          cd code
          cargo check --quiet --message-format=json | cargo-action-fmt

  cargo_format:
    name: Format Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt

      - name: Run 'cargo fmt'
        run: |
          cd code
          cargo fmt --all --message-format human -- --check

  cargo_clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - name: Install GitHub CI annotations formatter
        uses: olix0r/cargo-action-fmt@bf5a88a011c80288df07b34194f3f0abdb4b8f7d

      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy

      - name: Run Clippy
        run: |
          cd code
          cargo clippy --quiet --message-format=json | cargo-action-fmt

  cargo_doc:
    name: Documentation Check
    runs-on: ubuntu-20.04
    steps:
      - name: Install GitHub CI annotations formatter
        uses: olix0r/cargo-action-fmt@bf5a88a011c80288df07b34194f3f0abdb4b8f7d

      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2022-03-27

      - name: Run 'cargo doc'
        run: code code
          cargo doc --no-deps --message-format=json | cargo-action-fmt
