---
name: Security Audit

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - kernel/**/Cargo.toml
      - kernel/**/Cargo.lock
      - .github/workflows/security.yml
  schedule:
    - cron: 0 0 * * 6

defaults:
  run:
    shell: bash

env:
  RUST_TOOLCHAIN: nightly-2022-05-28

jobs:
  cargo-audit:
    name: Audit Cargo.lock
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Install 'cargo audit'
        run: cargo install cargo-audit

      - name: Run 'cargo audit'
        run: cargo audit --deny warnings
