---
name: Unit & Integration Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - code/src/**
    branches: ['**']
  push:
    paths: [code/src/**]
    branches: [master]

defaults:
  run:
    shell: bash

env:
  RUST_TOOLCHAIN: nightly-2022-05-28

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  unit-and-integration-tests:
    name: Run All Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Run 'cargo test'
        run: |
          cd code
          cargo install cargo2junit
          cargo test -- -Z unstable-options --format json --report-time \
            | cargo2junit >results.xml
      
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v1.37
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: code/results.xml
          check_name: Upload Test Results
          comment_title: Unit & Integration Test Results
