---
name: Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - code/src/**
    branches: ['**']
  push:
    paths: [code/src/**]
    branches: [master]

defaults:
  run:
    shell: bash

env:
  RUST_TOOLCHAIN: nightly-2022-05-28

jobs:
  unit-and-integration-tests:
    name: Run all unit- and integration-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3.0.0
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Run 'cargo test'
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --tests
